[package]
name = "plot_util"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
log_if = { version = "*", path = "../log_if" }
egui_plot.workspace = true
serde.workspace = true
num-traits = "0.2.19"

[dev-dependencies]
testresult.workspace = true
