[package]
name = "skytem_logs"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_plot = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5.1"
strum = "0.26.3"
strum_macros = "0.26.3"
byteorder = "1.5.0"
chrono = { version = "0.4.38", features = ["serde"] }
num-traits = "0.2.19"

[dev-dependencies]
testresult = { workspace = true }
